#training stage
sweep_id: ""
task:  "multitask_classifier" #subj_classifier
subj_model: "subj_classifier_v1"
multitask_model: "multitask_model_v1"
max_epochs: 1000
learning_rate_patience: 10
train_subj_with_weights: true

#evaluation stage
subj_chosen_model: "laced-sweep-3996"
multitask_chosen_model: ""
dataset_to_evaluate: 1
dataset_stage: "validate"