program: 3-sweep.py
name: LLMs
method: bayes
metric:
  name: recall/Val/Epoch
  goal: maximize
parameters:
  subj_loss_function:
    values: ["binary_cross_entropy"]
  multitask_loss_function:
    values: ["categorical_cross_entropy"]
  lr:
    max: 0.001
    min: 0.00001
  batch_size:
    values: [8, 16, 32, 64, 128]
  subj_weight_value:
    max: 4.0
    min: 1.0
