program: 3-sweep.py
name: LLMs
method: bayes
metric:
  name: acc/Train
  goal: maximize
parameters:
  loss_function:
    values: ["binary_cross_entropy"]
  lr:
    max: 0.001
    min: 0.00001
  batch_size:
    values: [8, 16, 32, 64, 128]
